# Generated by Django 5.0.6 on 2024-07-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default=None, max_length=100, null=True)),
                ("slug", models.SlugField(default=None, null=True, unique=True)),
                ("contact", models.CharField(max_length=100, null=True)),
                ("email", models.EmailField(max_length=300, null=True)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=100)),
                ("slug", models.SlugField(default=None, null=True, unique=True)),
                (
                    "image",
                    models.FileField(
                        default=None, max_length=255, null=True, upload_to="staffs/"
                    ),
                ),
                ("designation", models.CharField(default=None, max_length=100)),
                ("contact", models.CharField(max_length=100, null=True)),
                ("email", models.EmailField(max_length=300, null=True)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("mayor", "mayor"),
                            ("deputy-mayor", "deputy-mayor"),
                            ("Deputy Secretary", "Deputy Secretary"),
                            ("Branch Officer", "Branch Officer"),
                            ("Accounts Officer", "Accounts Officer"),
                            ("engineer", "engineer"),
                        ],
                        default=None,
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
