# Generated by Django 5.0.6 on 2024-07-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default=None, max_length=100, null=True)),
                ("slug", models.SlugField(default=None, null=True, unique=True)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Members",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=100)),
                ("slug", models.SlugField(default=None, null=True, unique=True)),
                ("designation", models.CharField(default=None, max_length=100)),
                (
                    "memberOf",
                    models.CharField(
                        choices=[
                            ("electionOfficial", "electionOfficial"),
                            ("multipalStaffs", "multipalStaffs"),
                            ("wardMembers", "wardMembers"),
                        ],
                        default=None,
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
