# Generated by Django 5.0.6 on 2024-07-08 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Members",
            new_name="Member",
        ),
    ]
