# Generated by Django 5.0.6 on 2024-07-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_rename_members_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="contact",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="email",
            field=models.EmailField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="image",
            field=models.FileField(
                default=None, max_length=255, null=True, upload_to="staffs/"
            ),
        ),
    ]
