# Generated by Django 5.0.6 on 2024-07-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_member_contact_member_email_member_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="contact",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="about",
            name="email",
            field=models.EmailField(max_length=300, null=True),
        ),
    ]
