# Generated by Django 5.0.6 on 2024-07-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_member_category_alter_member_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="category",
            field=models.CharField(
                choices=[
                    ("electionOfficial", "electionOfficial"),
                    ("multipalStaffs", "multipalStaffs"),
                    ("wardMembers", "wardMembers"),
                ],
                default=None,
                max_length=50,
                null=True,
            ),
        ),
    ]
