# Generated by Django 5.0.6 on 2024-07-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProgramProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default=None, max_length=100)),
                ("slug", models.SlugField(default=None, null=True, unique=True)),
                (
                    "file",
                    models.FileField(
                        default=None,
                        max_length=255,
                        null=True,
                        upload_to="programProject/",
                    ),
                ),
                ("dateTime", models.DateField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("budgetProgram", "budgetProgram"),
                            ("PlanningProject", "PlanningProject"),
                        ],
                        default=None,
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
